---
language: objective-c

before_install: 
# - brew update
 
install: 
# - brew upgrade xctool
 - sudo easy_install cpp-coveralls
# - curl -sL https://gist.github.com/henrikhodne/7ac6d02ff9a24a94720c/raw/install_appledoc.sh | sh

script: 
 - xctool -project PL.xcodeproj -scheme "Static Library" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - appledoc -o /tmp .

after_success:
#  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
