---
language: objective-c
osx_image: xcode7

install: 
 - sudo easy_install cpp-coveralls

script: 
 - xctool -project ProductLayerSDK.xcodeproj -scheme "PL Static Library (iOS)" build test -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO -configuration Coverage
 - appledoc -o /tmp .

after_success:
 - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
